name: penalties
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  intl: ^0.17.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.2
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
